-- 코드를 입력하세요
SELECT 
    B.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(BS.SALES * B.PRICE) TOTAL_SALES 
FROM 
    BOOK B
JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN BOOK_SALES BS ON B.BOOK_ID = BS.BOOK_ID
WHERE 
    DATE_FORMAT(BS.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY 
    B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY
    B.AUTHOR_ID, B.CATEGORY DESC;


