-- 코드를 입력하세요
SELECT CATEGORY, PRICE MAX_PRICE, PRODUCT_NAME FROM FOOD_PRODUCT
WHERE(CATEGORY = '과자' OR CATEGORY = '국' OR CATEGORY = '김치' OR CATEGORY = '식용유') 
AND PRICE = (
SELECT MAX(PRICE) FROM FOOD_PRODUCT FP2
WHERE FP2.CATEGORY = FOOD_PRODUCT.CATEGORY) 
ORDER BY MAX_PRICE DESC;
